CUDA_VISIBLE_DEVICES=0 \
torchrun --nproc_per_node=1 --master_port 18340 train_downstream.py \
    --Train_csv_path '/root/autodl-tmp/VQA_RAD/Task_COT_New_related_final.csv' \
    --Eval_csv_path '/root/autodl-tmp/VQA_RAD/testset.csv' \
    --output_dir /root/autodl-tmp/Uni/Results/QA_no_pretrain_no_aug-test2 \
    --run_name QA_no_pretrain_no_aug-test2 \
    --num_train_epochs 10 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    --load_best_model_at_end True \
    --save_total_limit 2 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --deepspeed ./ds_config/ds_config_zero3_offload.json \
    --checkpointing false \
    --bf16 True \
    --tf32 True
